---

- name: Check if pmm-client is already configured
  command: pmm-admin list
  ignore_errors: true
  register: pmm_admin_list
  changed_when: false

- name: Creating connection to PMM Server - Protected Mode
  command: >
           pmm-admin config --server {{ pmm_client_server_host }}:{{ pmm_client_http_port}} 
           --server-user {{ pmm_client_server_username }} 
           --server-password {{ pmm_client_server_password }}
  when: pmm_admin_list.stdout.find('PMM client is not configured') != -1
  
