---

- name: Uninstall PMM Client in Debain
  apt: name=pmm-client state=absent 
  when: ansible_os_family == 'Debian' and pmm_client_UNINSTALL


- name: Uninstall PMM Client in RedHat
  yum: name=pmm-client state=absent 
  when: ansible_os_family == 'RedHat' and pmm_client_UNINSTALL
