---

- name: Check if pmm-client is already configured
  command: pmm-admin list
  ignore_errors: true
  register: pmm_admin_list
  changed_when: false

- name: Creating connection to PMM Server - Protected Mode
  command: >
           pmm-admin config
           --server-insecure-tls
           --server-url=https://{{ pmm_client_server_username }}:{{ pmm_client_server_password }}@{{ pmm_client_server_host }}:{{ pmm_client_https_port}}
  when: pmm_admin_list.stderr.find('pmm-agent is running, but not set up') != -1
  
