---

- name: Check if pmm-client is already configured
  command: pmm-admin list
  ignore_errors: true
  register: pmm_admin_list
  changed_when: false

- name: Creating connection to PMM Server - SSL Mode with selfsigned SSL
  command: >
           pmm-admin config --server {{ pmm_client_server_host }}:{{ pmm_client_https_port}} 
           --server-insecure-ssl
  when: (pmm_admin_list.stderr.find('pmm-agent is running, but not set up') != -1 and pmm_client_default_cert)
 
- name: Creating connection to PMM Server - SSL Mode with CA signed SSL
  command: >
           pmm-admin config --server {{ pmm_client_server_host }}:{{ pmm_client_https_port}}
           --server-ssl
  when: (pmm_admin_list.stderr.find('pmm-agent is running, but not set up') != -1 and not(pmm_client_default_cert)) 

