---

- name: Check if SELinux is set to enforced mode
  fail: msg=" SELinux is in 'enforced' mode. Change it to 'permissive' or 'disabled' in order to install PMM Client"
  when: ansible_selinux.mode == 'enforcing'

- name: Configure Percona repository
  yum:
    name: "{{ pmm_client_RedHat_repo }}"
    state: present

- name: Install PMM Client
  yum:
    name: pmm2-client
    state: present
