---

- name: Fetch percona repository package
  get_url:
    url: https://repo.percona.com/apt/percona-release_0.1-4.{{ facter_lsbdistcodename }}_all.deb
    dest: /tmp/percona-release_0.1-4.{{ facter_lsbdistcodename }}_all.deb

- name: Install Repository package
  command: "dpkg -i percona-release_0.1-4.$(lsb_release -sc)_all.deb chdir=/tmp creates={{ item }}"
  with_items:
    - /etc/apt/sources.list.d/percona-release.list

- name: Install pmm-client package
  apt: name=pmm-client state=present update_cache=yes

