---

- name: Fetch percona repository package
  get_url:
    url: "{{ pmm_client_Debian_repo }}"
    dest: "/tmp/percona-release_0.1-4.{{ ansible_distribution_release }}_all.deb"

- name: Install Repository package
  command: "dpkg -i percona-release_0.1-4.{{ ansible_distribution_release }}_all.deb chdir=/tmp creates={{ item }}"
  with_items:
    - /etc/apt/sources.list.d/percona-release.list

- name: Install pmm-client package
  apt: name=pmm-client state=present update_cache=yes

